Account Status
Suprcode/mir2 pull request #897
Opened 2024-01-07 17:04 UTC by JevLOMCN

Characters now have a status displayed for Online/Offline/Deleted.

Guild tab now displays "No Guild" if the character is not in a Guild.

2024-01-08 16:46 UTC, Suprcode requested changes

2024-01-08 16:46 UTC, Suprcode commented on Server.MirForms/Account/AccountInfoForm.cs
> +            foreach (var account in accounts)
instead of looping through accounts, use linq Sum - its quicker and cleaner

accounts.Where(x => !x.AdminAccount && !x.Banned).Sum(s => s.Gold)

2024-01-08 16:46 UTC, Suprcode commented on Server.MirForms/Account/AccountInfoForm.cs
> +            {
instead of looping through accounts, use linq Sum - its quicker and cleaner

accounts.Where(x => !x.AdminAccount && !x.Banned).Sum(s => s.Credit)

2024-01-10 18:17 UTC, JevLOMCN commented
Changes done for accountinfoform.

2024-01-11 08:41 UTC, merged